### ISSUE TITLE
Missing files

### ISSUE THREAD

**Issue by mimoralea** [LxzGordon/PECAN#3]
Hi,

I'm trying to reproduce your results. Unfortunately, there are some missing files in the following directory: https://github.com/LxzGordon/PECAN/tree/master/human_aware_rl/human_aware_rl/context

In particular, your `pbt_experiments.py` references this import: https://github.com/LxzGordon/PECAN/blob/master/human_aware_rl/human_aware_rl/experiments/pbt_experiments.py#L7
but test_level.py doesn't come in the `context` folder.

I replaced the import to use the other file that's in there, `model.py` but I don't get the same results.

Also, `pbt_experiments.py` has a problem in this line: https://github.com/LxzGordon/PECAN/blob/master/human_aware_rl/human_aware_rl/experiments/pbt_experiments.py#L93

It's referencing a variable, `embeddings` but there is no such variable there.

Any help would be appreciated it.

**Comment by mimoralea** [comment]
This has been reported already, but the `planners` directory is missing the function that allows us to download planners.

https://github.com/LxzGordon/PECAN/tree/master/human_aware_rl/overcooked_ai/overcooked_ai_py/data/planners

I ended up copying it from here: 

https://github.com/HumanCompatibleAI/overcooked_ai/tree/6eaceb0a9a2501f1b9fccbf4c7016d6662ed1108/overcooked_ai_py/data/planners

**Comment by LxzGordon** [comment]
Thanks for sharing the solution

**Comment by LxzGordon** [comment]
And we do not use script ```pbt_experiments.py``` to run experiments. Please refer to the usage part of [readme](https://github.com/LxzGordon/PECAN/tree/master).
